# Generated by Django 4.0.3 on 2022-06-01 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_post_category_alter_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='users_of_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', through='news.PostCategory', to='news.category'),
        ),
    ]
